# Generated by Django 3.2.9 on 2021-11-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
