# Generated by Django 3.2.9 on 2021-11-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('B', 'book'), ('M', 'music'), ('F', 'film'), ('O', 'other')], max_length=30),
        ),
    ]
