# Generated by Django 3.2.9 on 2021-11-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211104_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='must be greater than 0')]),
        ),
    ]
